---
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=black
    - python: 3.6
      env: TOXENV=py36

before_install:
  - python -m pip install --upgrade virtualenv

install:
  - pip install tox

script:
  - tox
